### ISSUE TITLE
Link "LIFT principle" in "1 module = 1 directory" rule?

### ISSUE THREAD

**Issue by jbmoelker** [voorhoede/riotjs-style-guide#13]
John Papa's [LIFT principle](https://github.com/johnpapa/angular-styleguide/tree/master/a1#application-structure-lift-principle) fits well within our "1 module = 1 directory" rule. Should we link to it or embed it in some way?

**Comment by petergoes** [comment]
I don't think LIFT is fully compatible with this guide. The F stands for Flat folder structure. In our guide we let the option open to nest modules. When we want to embrace the LIFT principle, we should be stricter in regards to the flat folder principle

**Comment by jbmoelker** [comment]
agreed. could lead to confusion. will leave it out.
