### ISSUE TITLE
Add "File templates and snippets"?

### ISSUE THREAD

**Issue by jbmoelker** [voorhoede/riotjs-style-guide#23]
Add "File templates and snippets" for editors like John Papa's [Angular file templates and snippets](https://github.com/johnpapa/angular-styleguide/tree/master/a1#file-templates-and-snippets)?

**Comment by phortuin** [comment]
Would only do this if we at de Voorhoede actually work with templates/snippets. Don't create them just for this guide; we wouldn't be eating our own dog food, which we _do_ for the rest of the guide

**Comment by jbmoelker** [comment]
I think we've managed fine without the file templates/snippets so far. So agreed. Will close.
