### ISSUE TITLE
The tag is the api

### ISSUE THREAD

**Issue by petergoes** [voorhoede/riotjs-style-guide#37]
Continuing the discussion of #36. Do we need a rule stating that the html acts as the api of the tag?

**Comment by jbmoelker** [comment]
I think we touch on this in the first rule about tag options ["Keep tag options primitive"](https://github.com/voorhoede/riotjs-style-guide#why-6):

> - By using an attribute for each option separately the tag has a clear and expressive API.
> - By using only primitives and functions as option values our tag APIs are similar to the APIs of native HTML(5) elements. 

And we have a full rule about it ["Document your tag API"](https://github.com/voorhoede/riotjs-style-guide#document-your-tag-api). So I would say this is sufficient.

**Comment by phortuin** [comment]
I concur, closed
