### ISSUE TITLE
Badge to indicate project is using RiotJS Style Guide?

### ISSUE THREAD

**Issue by jbmoelker** [voorhoede/riotjs-style-guide#38]
I think projects should indicate if the follow the RiotJS Style Guide conventions. Would be nice if they could do it with a badge.

![riotjs-style-guide](https://cloud.githubusercontent.com/assets/1516059/14014319/1b25e76a-f1b2-11e5-96be-963f9d1bff57.png)

Better design (SVG?) is welcome.

**Comment by phortuin** [comment]
Example of projects doing this for other style guides?

**Comment by jbmoelker** [comment]
@phortuin not the same, but the first one I could think of 
[![Awesome](https://cdn.rawgit.com/sindresorhus/awesome/d7305f38d29fed78fa85652e3a63e154dd8e8829/media/badge.svg)](https://github.com/sindresorhus/awesome)
https://github.com/sindresorhus/awesome/blob/master/media/

**Comment by petergoes** [comment]
something like: https://img.shields.io/badge/uses-riotjs--style--guide-ff0044.svg ?

**Comment by phortuin** [comment]
looks good, why the double dashes?

**Comment by jurgenbelien** [comment]
I like the idea of using the defacto standard of shields.io. However, I think we should define why we made certain choices in color or text-sequence:

I’m guessing we’d like a family of styleguides, Riot, jQuery, etc.
The shield.io describes a certain aspect of a project in a key:value way. ie. build:passing, coverage:80%
Following this pattern you’d end up with something like this:
https://img.shields.io/badge/styleguided-riot--style--guide-ff0044.svg
https://img.shields.io/badge/styleguided-jquery--style--guide-0769ad.svg

**Comment by phortuin** [comment]
so we'd claim a 'root' property? for technology that the world uses? pretty bold

**Comment by petergoes** [comment]
@phortuin the double dashes is something shield.io uses

**Comment by jurgenbelien** [comment]
@phortuin, Well then that's a strike against using shield.io at all, I feel.

**Comment by phortuin** [comment]
@jurgenbelien well i'm not against it, just not sure if we can live up to the expectations :) if so, let's do it, otherwise, no badge

**Comment by jbmoelker** [comment]
@phortuin's pretty SVG proposal:

![RiotJS Style Guide badge](https://rawgit.com/jbmoelker/f1a7a48c0966d2898af7/raw/e3a1fb6e9b1a072c4547aee2bd38bc5c1be4eed6/riotjs-style-guide-badge.svg)

**Comment by phortuin** [comment]
i'm not sure about my proposal though :) the key/value principle is better, because what do we do when we have a jquery style guide? or just replace RIOT with jQuery?

**Comment by jbmoelker** [comment]
yup, and we theme the left part in the theme of the framework / language / ...

**Comment by petergoes** [comment]
I'd like to see us using standardized things, because we are a company that values (web) standards. Having our custom cooked up badge feels kind of odd.
https://img.shields.io/badge/style_guide-riot--js-red.svg

**Comment by jbmoelker** [comment]
@petergoes this whole project is about standards. I think it's time for a bit of identity :) And I would stay away from "badge red" as I only know it as being used for "failing". Not the association I was going for.
