### ISSUE TITLE
Link to demos?

### ISSUE THREAD

**Issue by jbmoelker** [voorhoede/riotjs-style-guide#42]
Shall we link from the guide to the [RiotJS Demos repo](https://github.com/voorhoede/riotjs-demos#riotjs-demos-)? And if so, just a general reference, or specific ones like somewhere in ["Keep tag options simple" rule](https://github.com/voorhoede/riotjs-style-guide#keep-tag-options-primitive) to [`<range-slider>` demo](https://voorhoede.github.io/riotjs-demos/range-slider/range-slider.demo.html)?

@phortuin, @petergoes what do you think?

**Comment by petergoes** [comment]
I'd keep it general. Maybe something like:

> This guide is inspired by the AngularJS Style Guide by John Papa.
> View the [demos](https://github.com/voorhoede/riotjs-demos) that goes with this guide
