### ISSUE TITLE
extend "Module based development" with how to compile with "module definitions"?

### ISSUE THREAD

**Issue by jbmoelker** [voorhoede/riotjs-style-guide#46]
Should we add to the "[Module based development](https://github.com/voorhoede/riotjs-style-guide#module-based-development)" guideline, that you can compile your tags to support AMD and CommonJS module definitions using `riot --modular` (`riot -m`)?

[Riot Guide > AMD and CommonJS support](http://riotjs.com/guide/compiler/#amd-and-commonjs):

> Riot tags can be compiled with AMD (Asynchronous Module Definition) and CommonJS support. This configuration option is necessary if Riot is used with an AMD loader such as RequireJS or a CommonJS loader such as Browserify.

**Comment by phortuin** [comment]
As a tip, yes, not a recommendation

**Comment by jbmoelker** [comment]
@phortuin I agree on that. Just wondering if the "Module based development" guideline itself was not too high level to put something so specific there. I didn't know about the feature at first because its a bit hidden away, but is very useful when used in a larger setup using a module loader, for instance in test setup.

**Comment by phortuin** [comment]
I think it fits perfectly, it helps devs adopt this guideline no matter their current module loading setup

**Comment by jbmoelker** [comment]
Good. Will create a PR.
