### ISSUE TITLE
Use lexical this outside tag scope

### ISSUE THREAD

**Issue by MartinMuzatko** [voorhoede/riotjs-style-guide#49]
https://github.com/voorhoede/riotjs-style-guide#assign-this-to-tag

With es6 lexical this syntax `() => {}` or `function() {}.bind(this)` it should be very easy to avoid something as redundant as `var that = this` or `const tag = this`

**Comment by jbmoelker** [comment]
Agree both are possible. Using `const tag = this` is simply our preference over `function() {}.bind(this)`. 

Also based on [Angular Style Guide > `var vm = this;`](https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md#controlleras-with-vm).
