### ISSUE TITLE
input of type date is not working

### ISSUE THREAD

**Issue by bogdanmata** [voorhoede/riotjs-style-guide#60]
for a custom tag the following does not get bind

<tag-custom>
<input type="date" value="{aDate}">

<script>
this.aDate = new Date();
</script>
</tag-custom>

**Comment by joshgillies** [comment]
`<input type="date" />` accepts a date value in the form of `yyyy-mm-dd`. If you want to bind a custom date value to your tag eg. `<input type="date" value="{ aDate }" />` you'll have to ensure `aDate` is in the above format.

Also, this might not be the best place to post an issue like this. I'd suggest logging this sort of thing against riot directly. https://github.com/riot/riot/issues
